name: Public AUR gamescope-sk

on:
  push:
    paths:
        - "pkgbuild/gamescope-sk/PKGBUILD"
  workflow_dispatch:

jobs:
  public_aur:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Changed log
        id: get_log
        run: |
          logdfile="pkgbuild/gamescope-sk/changelog.txt"
          if [ -f $logdfile ]; then
            echo "::set-output name=changed_log::$(cat $logdfile | head -n 1)"
          else
            echo "::set-output name=changed_log::$(git log --pretty=format:"%h %s" ${{ github.event.before }}..${{ github.sha }})"
          fi

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        with:
          pkgname: gamescope-sk
          pkgbuild: pkgbuild/gamescope-sk/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ steps.get_log.outputs.changed_log }}
          ssh_keyscan_types: rsa,ecdsa,ed25519
