name: Public AUR sk ChimeraOS Addon

on:
  push:
    paths:
      - "pkgbuild/sk-chos-addon/PKGBUILD"
      - "pkgbuild/sk-chos-addon/*.install"
    # tags:
    #   - "v*"
  workflow_dispatch:

env:
  COMMIT_LOG: Update AUR

jobs:
  public_aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update PKGBUILD
        id: update
        run: |
          cd pkgbuild/sk-chos-addon
          git clone --depth 1 https://github.com/honjow/sk-chos-config.git && cd sk-chos-config
          git fetch --unshallow
          pkgver=$(git describe --tags --abbrev=0 | sed 's/^v//')
          echo "Updating PKGBUILD to version $pkgver"
          git_log=$(git log --pretty=format:"%h %s" | head -n 1)
          if [ -n "$git_log" ]; then
            echo "COMMIT_LOG=$git_log" >> $GITHUB_ENV
          fi
          cd ..
          sed -i "s/^pkgver=.*/pkgver=$pkgver/" PKGBUILD
          cat PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: sk-chos-addon
          pkgbuild: pkgbuild/sk-chos-addon/PKGBUILD
          assets: pkgbuild/sk-chos-addon/*.install
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ env.COMMIT_LOG }}
          ssh_keyscan_types: rsa,ecdsa,ed25519
