name: Public AUR moonlight-qt-axi-appimage

on:
  push:
    paths:
        - "pkgbuild/moonlight-qt-axi-appimage/PKGBUILD"
        - "pkgbuild/moonlight-qt-axi-appimage/*.sh"
  workflow_dispatch:

jobs:
  public_aur:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: moonlight-qt-axi-appimage
          pkgbuild: pkgbuild/moonlight-qt-axi-appimage/PKGBUILD
          assets: pkgbuild/moonlight-qt-axi-appimage/*.sh
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
